apiVersion: v1
kind: Service
metadata:
  name: mobilenet-classifier-service
spec:
  selector:
    app: mobilenet-classifier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
